import React from 'react';
import { RefreshCw } from 'lucide-react';
import { Match } from '../../types/types';
import StatusBadge from '../ui/StatusBadge';

interface MatchesTableProps {
  matches: Match[];
  onUpdateStatus: (id: number | string, status: string) => void;
  onGenerateMatches: () => void;
}

const MatchesTable: React.FC<MatchesTableProps> = ({
  matches,
  onUpdateStatus,
  onGenerateMatches
}) => {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Automated Matches</h2>
          <p className="text-gray-600">Matches generated by Levenshtein Distance algorithm</p>
        </div>
        <button 
          onClick={onGenerateMatches}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2"
        >
          <RefreshCw size={18} />
          Regenerate Matches
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <div className="space-y-4">
          {matches.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              No matches found. Try regenerating.
            </div>
          ) : (
            matches.map((match) => (
              <div key={match.id} className="p-4 border border-gray-200 rounded-lg hover:bg-gray-50">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-4">
                    <div className="text-center">
                      <div className="font-bold text-lg text-blue-600">{match.matchScore}%</div>
                      <div className="text-xs text-gray-500">Similarity</div>
                    </div>
                    <div className="flex-1">
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <div className="font-medium text-red-600">Lost Item</div>
                          <div className="text-sm">{match.lostPost.title}</div>
                          <div className="text-xs text-gray-500">
                            {match.lostPost.description.substring(0, 50)}...
                          </div>
                        </div>
                        <div>
                          <div className="font-medium text-green-600">Found Item</div>
                          <div className="text-sm">{match.foundPost.title}</div>
                          <div className="text-xs text-gray-500">
                            {match.foundPost.description.substring(0, 50)}...
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <StatusBadge status={match.status} />
                </div>
                <div className="flex items-center justify-between">
                  <div className="text-sm text-gray-500">
                    Generated on {new Date(match.createdAt).toLocaleDateString()}
                  </div>
                  <div className="flex items-center gap-2">
                    {match.status === 'pending' && (
                      <>
                        <button
                          onClick={() => onUpdateStatus(match.id, 'confirmed')}
                          className="px-3 py-1 bg-green-100 text-green-700 rounded-lg hover:bg-green-200 text-sm"
                        >
                          Confirm Match
                        </button>
                        <button
                          onClick={() => onUpdateStatus(match.id, 'rejected')}
                          className="px-3 py-1 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 text-sm"
                        >
                          Reject
                        </button>
                      </>
                    )}
                    <button className="px-3 py-1 bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200 text-sm">
                      Details
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};

export default MatchesTable;