import React from 'react';
import { RefreshCw, Eye, Shield, AlertCircle, CheckCircle, XCircle } from 'lucide-react';
import { Match } from '../../types/types';
import StatusBadge from '../ui/StatusBadge';

interface MatchesTableProps {
  matches: Match[];
  onUpdateStatus: (id: number | string, status: string) => void;
  onGenerateMatches: () => void;
}

const MatchesTable: React.FC<MatchesTableProps> = ({
  matches,
  onUpdateStatus,
  onGenerateMatches
}) => {
  const [selectedMatch, setSelectedMatch] = React.useState<Match | null>(null);

  // Count matches that need review
  const needsReviewCount = matches.filter(m => m.status === 'admin_review' || m.status === 'pending').length;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Automated Matches ({matches.length})</h2>
          <p className="text-gray-600">
            Matches generated by Levenshtein Distance algorithm
            {needsReviewCount > 0 && (
              <span className="ml-2 px-2 py-1 bg-purple-100 text-purple-700 rounded-full text-sm font-medium">
                {needsReviewCount} awaiting review
              </span>
            )}
          </p>
        </div>
        <button 
          onClick={onGenerateMatches}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center gap-2"
        >
          <RefreshCw size={18} />
          Regenerate Matches
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <div className="space-y-4">
          {matches.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              No matches found. Try regenerating.
            </div>
          ) : (
            matches.map((match) => (
              <div key={match.id} className={`p-4 border rounded-lg hover:bg-gray-50 ${
                match.status === 'admin_review' 
                  ? 'border-purple-400 bg-purple-50 ring-2 ring-purple-200' 
                  : (match.status === 'pending' || match.status === 'pending_approval') 
                    ? 'border-yellow-300 bg-yellow-50' 
                    : 'border-gray-200'
              }`}>
                {/* Status Banner */}
                {match.status === 'admin_review' && (
                  <div className="mb-3 p-2 bg-purple-100 border border-purple-300 rounded-lg flex items-center gap-2">
                    <AlertCircle className="text-purple-600" size={18} />
                    <span className="text-sm font-bold text-purple-700">
                      READY FOR REVIEW - Both users have submitted verification details
                    </span>
                  </div>
                )}
                {(match.status === 'pending' || match.status === 'pending_approval') && (
                  <div className="mb-2 text-xs font-bold text-yellow-700 uppercase tracking-wide flex items-center gap-2">
                    <span className="w-2 h-2 bg-yellow-600 rounded-full animate-pulse"></span>
                    Waiting for {match.lostUserConfirmation && !match.foundUserConfirmation ? 'Finder' : 'Owner'} Confirmation
                  </div>
                )}
                
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-4">
                    <div className="text-center">
                      <div className="font-bold text-lg text-blue-600">{match.matchScore}%</div>
                      <div className="text-xs text-gray-500">Similarity</div>
                    </div>
                    <div className="flex-1">
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <div className="font-medium text-red-600 flex items-center gap-1">
                            Lost Item
                            {match.lostUserConfirmation && (
                              <CheckCircle className="text-green-500" size={14} />
                            )}
                          </div>
                          <div className="text-sm">{match.lostPost.title}</div>
                          <div className="text-xs text-gray-500">
                            {match.lostPost.description.substring(0, 50)}...
                          </div>
                        </div>
                        <div>
                          <div className="font-medium text-green-600 flex items-center gap-1">
                            Found Item
                            {match.foundUserConfirmation && (
                              <CheckCircle className="text-green-500" size={14} />
                            )}
                          </div>
                          <div className="text-sm">{match.foundPost.title}</div>
                          <div className="text-xs text-gray-500">
                            {match.foundPost.description.substring(0, 50)}...
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <StatusBadge status={match.status} />
                </div>

                {/* Quick Preview of Confirmations */}
                {(match.lostUserConfirmation || match.foundUserConfirmation) && (
                  <div className="mb-3 p-3 bg-gray-50 rounded-lg">
                    <div className="text-xs font-semibold text-gray-600 mb-2">Verification Details Available:</div>
                    <div className="grid grid-cols-2 gap-4 text-xs">
                      <div className={`p-2 rounded ${match.lostUserConfirmation ? 'bg-red-50 border border-red-200' : 'bg-gray-100'}`}>
                        <div className="flex items-center gap-1 mb-1">
                          <Shield size={12} className={match.lostUserConfirmation ? 'text-red-600' : 'text-gray-400'} />
                          <span className="font-medium">Owner's Proof</span>
                        </div>
                        {match.lostUserConfirmation ? (
                          <span className="text-green-600">✓ Submitted</span>
                        ) : (
                          <span className="text-gray-400">Not yet submitted</span>
                        )}
                      </div>
                      <div className={`p-2 rounded ${match.foundUserConfirmation ? 'bg-green-50 border border-green-200' : 'bg-gray-100'}`}>
                        <div className="flex items-center gap-1 mb-1">
                          <Eye size={12} className={match.foundUserConfirmation ? 'text-green-600' : 'text-gray-400'} />
                          <span className="font-medium">Finder's Observations</span>
                        </div>
                        {match.foundUserConfirmation ? (
                          <span className="text-green-600">✓ Submitted</span>
                        ) : (
                          <span className="text-gray-400">Not yet submitted</span>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-between">
                  <div className="text-sm text-gray-500">
                    Generated on {new Date(match.createdAt).toLocaleDateString()}
                  </div>
                  <div className="flex items-center gap-2">
                    {(match.status === 'admin_review' || match.status === 'pending' || match.status === 'pending_approval') && (
                      <>
                        <button
                          onClick={() => {
                            if (window.confirm("Are you sure you want to approve this match? This will mark both the lost and found items as resolved.")) {
                              onUpdateStatus(match.id, 'confirmed');
                            }
                          }}
                          className="px-3 py-1 bg-green-100 text-green-700 rounded-lg hover:bg-green-200 text-sm font-medium"
                        >
                          Approve Match
                        </button>
                        <button
                          onClick={() => {
                              const reason = prompt("Enter rejection reason:");
                              if (reason) {
                                  if (window.confirm("Are you sure you want to reject this match?")) {
                                    onUpdateStatus(match.id, 'rejected'); 
                                  }
                              }
                          }}
                          className="px-3 py-1 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 text-sm font-medium"
                        >
                          Reject
                        </button>
                      </>
                    )}
                    <button 
                        onClick={() => setSelectedMatch(match)}
                        className={`px-3 py-1 rounded-lg text-sm font-medium ${
                          match.status === 'admin_review' 
                            ? 'bg-purple-600 text-white hover:bg-purple-700' 
                            : 'bg-blue-100 text-blue-700 hover:bg-blue-200'
                        }`}
                    >
                      {match.status === 'admin_review' ? 'Review Details' : 'Details'}
                    </button>
                  </div>
                </div>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Details Modal with Verification Comparison */}
      {selectedMatch && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl shadow-xl max-w-5xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex justify-between items-center p-6 border-b bg-gradient-to-r from-blue-50 to-purple-50">
              <div>
                <h3 className="text-xl font-bold">Match Details</h3>
                <p className="text-sm text-gray-600">Match Score: {selectedMatch.matchScore}%</p>
              </div>
              <button onClick={() => setSelectedMatch(null)} className="text-gray-500 hover:text-gray-700 text-2xl">✕</button>
            </div>
            
            <div className="p-6">
              {/* Item Comparison */}
              <div className="grid md:grid-cols-2 gap-8 mb-8">
                {/* Lost Side */}
                <div className="space-y-4">
                  <div className="font-bold text-lg text-red-600 border-b pb-2">Looking For (Lost)</div>
                  {selectedMatch.lostPost.imageUrl && (
                    <img src={selectedMatch.lostPost.imageUrl} className="w-full h-48 object-cover rounded-lg"/>
                  )}
                  <div>
                    <span className="font-semibold block">Title:</span> {selectedMatch.lostPost.title}
                  </div>
                  <div>
                    <span className="font-semibold block">Description:</span> {selectedMatch.lostPost.description}
                  </div>
                  <div>
                    <span className="font-semibold block">Location:</span> {selectedMatch.lostPost.location}
                  </div>
                  <div>
                    <span className="font-semibold block">Date:</span> {new Date(selectedMatch.lostPost.date).toLocaleDateString()}
                  </div>
                  <div className="bg-gray-50 p-3 rounded">
                    <span className="font-semibold block text-sm">User Info:</span>
                    <div className="text-sm">{selectedMatch.lostPost.user.name}</div>
                    <div className="text-sm">{selectedMatch.lostPost.user.email}</div>
                    <div className="text-sm">{selectedMatch.lostPost.user.phone}</div>
                  </div>
                </div>

                {/* Found Side */}
                <div className="space-y-4">
                  <div className="font-bold text-lg text-green-600 border-b pb-2">Found Item</div>
                  {selectedMatch.foundPost.imageUrl && (
                    <img src={selectedMatch.foundPost.imageUrl} className="w-full h-48 object-cover rounded-lg"/>
                  )}
                  <div>
                    <span className="font-semibold block">Title:</span> {selectedMatch.foundPost.title}
                  </div>
                  <div>
                    <span className="font-semibold block">Description:</span> {selectedMatch.foundPost.description}
                  </div>
                  <div>
                    <span className="font-semibold block">Location:</span> {selectedMatch.foundPost.location}
                  </div>
                  <div>
                    <span className="font-semibold block">Date:</span> {new Date(selectedMatch.foundPost.date).toLocaleDateString()}
                  </div>
                  <div className="bg-gray-50 p-3 rounded">
                    <span className="font-semibold block text-sm">User Info:</span>
                    <div className="text-sm">{selectedMatch.foundPost.user.name}</div>
                    <div className="text-sm">{selectedMatch.foundPost.user.email}</div>
                    <div className="text-sm">{selectedMatch.foundPost.user.phone}</div>
                  </div>
                </div>
              </div>

              {/* Verification Details Comparison */}
              {(selectedMatch.lostUserConfirmation || selectedMatch.foundUserConfirmation) && (
                <div className="border-t pt-6">
                  <h4 className="text-lg font-bold mb-4 flex items-center gap-2">
                    <AlertCircle className="text-purple-600" size={20} />
                    Verification Details Comparison
                  </h4>
                  
                  <div className="grid md:grid-cols-2 gap-6">
                    {/* Owner's Proof */}
                    <div className="border border-red-200 rounded-lg overflow-hidden">
                      <div className="bg-red-50 px-4 py-3 border-b border-red-200">
                        <div className="flex items-center gap-2">
                          <Shield className="text-red-600" size={18} />
                          <span className="font-semibold text-red-800">Owner's Ownership Proof</span>
                        </div>
                        {selectedMatch.lostUserConfirmedAt && (
                          <div className="text-xs text-red-600 mt-1">
                            Submitted: {new Date(selectedMatch.lostUserConfirmedAt).toLocaleString()}
                          </div>
                        )}
                      </div>
                      <div className="p-4 space-y-3">
                        {selectedMatch.lostUserConfirmation ? (
                          <>
                            {selectedMatch.lostUserConfirmation.uniqueMarks && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Unique Marks:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.uniqueMarks}</p>
                              </div>
                            )}
                            {selectedMatch.lostUserConfirmation.itemContents && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Item Contents:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.itemContents}</p>
                              </div>
                            )}
                            {selectedMatch.lostUserConfirmation.distinguishingFeatures && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Distinguishing Features:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.distinguishingFeatures}</p>
                              </div>
                            )}
                            {selectedMatch.lostUserConfirmation.personalIdentifiers && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Personal Identifiers:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.personalIdentifiers}</p>
                              </div>
                            )}
                            {selectedMatch.lostUserConfirmation.hiddenDetails && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Hidden Details:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.hiddenDetails}</p>
                              </div>
                            )}
                            {selectedMatch.lostUserConfirmation.additionalNotes && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Additional Notes:</span>
                                <p className="text-sm">{selectedMatch.lostUserConfirmation.additionalNotes}</p>
                              </div>
                            )}
                          </>
                        ) : (
                          <div className="text-center py-6 text-gray-400">
                            <Shield className="mx-auto mb-2" size={24} />
                            <p>Not yet submitted</p>
                          </div>
                        )}
                      </div>
                    </div>

                    {/* Finder's Observations */}
                    <div className="border border-green-200 rounded-lg overflow-hidden">
                      <div className="bg-green-50 px-4 py-3 border-b border-green-200">
                        <div className="flex items-center gap-2">
                          <Eye className="text-green-600" size={18} />
                          <span className="font-semibold text-green-800">Finder's Observations</span>
                        </div>
                        {selectedMatch.foundUserConfirmedAt && (
                          <div className="text-xs text-green-600 mt-1">
                            Submitted: {new Date(selectedMatch.foundUserConfirmedAt).toLocaleString()}
                          </div>
                        )}
                      </div>
                      <div className="p-4 space-y-3">
                        {selectedMatch.foundUserConfirmation ? (
                          <>
                            {selectedMatch.foundUserConfirmation.exactLocation && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Exact Location Found:</span>
                                <p className="text-sm">{selectedMatch.foundUserConfirmation.exactLocation}</p>
                              </div>
                            )}
                            {selectedMatch.foundUserConfirmation.conditionWhenFound && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Condition When Found:</span>
                                <p className="text-sm">{selectedMatch.foundUserConfirmation.conditionWhenFound}</p>
                              </div>
                            )}
                            {selectedMatch.foundUserConfirmation.visibleFeatures && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Visible Features:</span>
                                <p className="text-sm">{selectedMatch.foundUserConfirmation.visibleFeatures}</p>
                              </div>
                            )}
                            {selectedMatch.foundUserConfirmation.accessoriesFound && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Items Found With It:</span>
                                <p className="text-sm">{selectedMatch.foundUserConfirmation.accessoriesFound}</p>
                              </div>
                            )}
                            {selectedMatch.foundUserConfirmation.additionalNotes && (
                              <div>
                                <span className="text-xs font-semibold text-gray-500 uppercase">Additional Notes:</span>
                                <p className="text-sm">{selectedMatch.foundUserConfirmation.additionalNotes}</p>
                              </div>
                            )}
                          </>
                        ) : (
                          <div className="text-center py-6 text-gray-400">
                            <Eye className="mx-auto mb-2" size={24} />
                            <p>Not yet submitted</p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Action Footer */}
            <div className="p-6 border-t bg-gray-50 flex justify-between items-center">
              <button onClick={() => setSelectedMatch(null)} className="px-4 py-2 text-gray-600 hover:bg-gray-200 rounded-lg">
                Close
              </button>
              
              {(selectedMatch.status === 'admin_review' || selectedMatch.status === 'pending' || selectedMatch.status === 'pending_approval') && (
                <div className="flex gap-3">
                  <button
                    onClick={() => {
                      if (window.confirm("Are you sure you want to reject this match?")) {
                        onUpdateStatus(selectedMatch.id, 'rejected');
                        setSelectedMatch(null);
                      }
                    }}
                    className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 flex items-center gap-2"
                  >
                    <XCircle size={18} />
                    Reject Match
                  </button>
                  <button
                    onClick={() => {
                      if (window.confirm("Are you sure you want to approve this match? Both items will be marked as resolved.")) {
                        onUpdateStatus(selectedMatch.id, 'confirmed');
                        setSelectedMatch(null);
                      }
                    }}
                    className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center gap-2"
                  >
                    <CheckCircle size={18} />
                    Approve Match
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default MatchesTable;